Added SN+BAO+CMB examples
LSSTDESC/firecrown pull request #188
Opened 2022-10-09 10:41 UTC by am610

Added `ini` file demonstrating how `SN+BAO+CMB` chains can be produced.

2022-10-10 15:31 UTC, marcpaterno requested changes

2022-10-10 15:31 UTC, marcpaterno commented on examples/srd_sn/sn_srd_planck_bao.ini
> +planck_path = ${CSL_DIR}/likelihood/planck2018/baseline/plc_3.0
`planck_path` is usually used to set paths to the Planck data, as specified elsewhere in the file. I don't see it used -- is that an oversight, or is the `planck_path` parameter not needed?

2022-10-11 20:12 UTC, marcpaterno requested changes
I am not sure I'm interpreting the GitHub web interface correctly, but you may have accidentally committed a file `#generate_sn_data.py#` (perhaps an editor backup file)?

Please check this, and if it is correct, remove the file from the pull request. If it is not correct,, please post a follow-up comment saying this is the case.

2022-10-12 03:39 UTC, am610 commented
> I am not sure I'm interpreting the GitHub web interface correctly, but you may have accidentally committed a file `#generate_sn_data.py#` (perhaps an editor backup file)?
> 
> Please check this, and if it is correct, remove the file from the pull request. If it is not correct,, please post a follow-up comment saying this is the case.

Please check, I think the `#generate_sn_data.py#` file is successfully removed now.

2022-10-12 03:42 UTC, marcpaterno approved these changes

2022-10-12 03:43 UTC, merged